name: Output
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"
    outputs:
      result: ${{ steps.source.outputs.result }}
  after:
    runs-on: ubuntu-latest
    needs: [share]
    steps:
      - env:
          RESULT: ${{ needs.share.outputs.result }}
